export const FETCH_MENULIST_STARTED = 'FETCH_MENULIST_STARTED'
export const FETCH_MENULIST_SUCCESS = 'FETCH_MENULIST_SUCCESS'
export const FETCH_MENULIST_FAILURE = 'FETCH_MENULIST_FAILURE'

export const CREATE_NEW_FOLDER = 'CREATE_NEW_FOLDER'
export const DELETE_FOLDER = 'DELETE_FOLDER'
export const CHANGE_FOLDER = 'CHANGE_FOLDER'