export const FETCH_MENULIST_STARTED = 'FETCH_MENULIST_STARTED'
export const FETCH_MENULIST_SUCCESS = 'FETCH_MENULIST_SUCCESS'
export const FETCH_MENULIST_FAILURE = 'FETCH_MENULIST_FAILURE'

export const FETCH_CARDLIST_STARTED = 'FETCH_CARDLIST_STARTED'
export const FETCH_CARDLIST_SUCCESS = 'FETCH_CARDLIST_SUCCESS'
export const FETCH_CARDLIST_FAILURE = 'FETCH_CARDLIST_FAILURE'

export const CREATE_NEW_FOLDER = 'CREATE_NEW_FOLDER'
export const DELETE_FOLDER = 'DELETE_FOLDER'
export const CHANGE_FOLDER = 'CHANGE_FOLDER'

export const CREATE_NEW_CARD = 'CREATE_NEW_CARD'
export const DELETE_CARD = 'DELETE_CARD'
export const CHANGE_CARD_TITLE = 'CHANGE_CARD_TITLE'


